services:
  - type: web
    name: academia-ingles
    env: node
    buildCommand: |
      npm uninstall bcrypt
      npm install bcrypt@5.1.1
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false